# Generated by Django 5.0 on 2023-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя и фамилия сотрудника', max_length=50)),
                ('phone', models.CharField(help_text='Телефон сотрудника', max_length=20)),
                ('salary', models.FloatField(help_text='Процентная ставка')),
            ],
            options={
                'verbose_name': 'Сторудник',
                'verbose_name_plural': 'Сторудники',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.FloatField(blank=True, default=None, help_text='Скидка', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Имя клиента', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Телефон клиента', max_length=20),
        ),
    ]
