# Generated by Django 5.0 on 2023-12-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_worker_alter_user_options_user_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.CharField(help_text='Заголовок', max_length=50)),
                ('category_mod', models.CharField(blank=True, help_text='Модель оборудования', max_length=100, null=True)),
                ('mod', models.TextField(help_text='Введите характер неисправности')),
                ('date_out', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('master_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
